# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171106_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
    ]
