# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20171106_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.IntegerField(),
        ),
    ]
